/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorInventario;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import modelos.InventarioProducto;

/**
 *
 * @author Angel Basto Gonzalez
 */
public class VentanaInventario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInventario
     */
    public static VentanaInventario ventanaInventario;
    private ControladorInventario controladorInventario = new ControladorInventario();
    private DefaultTableModel modelo;
    
    private VentanaInventario() {
        initComponents();
        setLocationRelativeTo(null);
        controladorInventario = new ControladorInventario();
        inicializarTablaInsumos();
        setVisible(true);
    }
    
    public static VentanaInventario obtenerUnicaVentanaInventario(){
        if(ventanaInventario == null){
            ventanaInventario = new VentanaInventario();
        }else{
            ventanaInventario.setVisible(true);
        }
        return ventanaInventario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInsumos = new javax.swing.JTable();
        btnAgregarExistencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario ");

        tituloVent.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        tituloVent.setText("Inventario");

        tablaInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInsumos);

        btnAgregarExistencias.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnAgregarExistencias.setText("Agregar Insumos");
        btnAgregarExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExistenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnAgregarExistencias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloVent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarExistencias)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarExistenciasActionPerformed
        VentanaModificacionInventario.obtenerUnicaVentanaMoficacionInventario();
    }//GEN-LAST:event_btnAgregarExistenciasActionPerformed

    public void inicializarTablaInsumos(){        
        String[] cabecera = {"Nombre", "Cantidad"};
        Object[][] cuerpo ={};
        
        modelo = new DefaultTableModel(cuerpo, cabecera);
        
        tablaInsumos.setModel(modelo);
    }
    
    public void mostrarInventarioProductos(ArrayList<InventarioProducto> productos){
        int LIMPIAR_FILAS = 0;
        modelo.setRowCount(LIMPIAR_FILAS);
        for(int i=0; i<productos.size(); i++){
            Object datosProductos[] = {productos.get(i).getNombre(), 
                productos.get(i).getExistencias()};
            
            modelo.addRow(datosProductos);
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarExistencias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInsumos;
    private javax.swing.JLabel tituloVent;
    // End of variables declaration//GEN-END:variables
}
